spring:
  datasource:
    url: jdbc:h2:mem:nisumdb
    username: nisumdb
    password: n1$umDB
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true